### ISSUE TITLE
Breaking change in 0.48.0

### ISSUE THREAD

**Issue by nicolaasuni-vonage** [prometheus/common#577] opened 2024-02-23 11:42 UTC
The latest version 0.48.0 breaks an existing workflow.
https://github.com/prometheus/common/pull/576

After upgrading to `github.com/prometheus/common v0.48.0` and running golangci-lint on the source code I get the following error:

```
[...]/gosrvlib/target/binutil/golangci-lint run --exclude-use-default=false --max-issues-per-linter 0 --max-same-issues 0 ./pkg/...
WARN [runner] Can't run linter goanalysis_metalinter: buildssa: failed to load package testutil: could not load export data: no export data for "github.com/prometheus/client_golang/prometheus/testutil" 
ERRO Running error: can't run linter goanalysis_metalinter
buildssa: failed to load package testutil: could not load export data: no export data for "github.com/prometheus/client_golang/prometheus/testutil" 
```

To reproduce:

```
git clone https://github.com/Vonage/gosrvlib.git
cd gosrvlib
make modupdate x
```

**Comment by beorn7** [comment] 2024-02-23 13:17
@ywwg could you check if there is an easy fix?

I can look into this next week, but perhaps you can beat me to it.

**Comment by ywwg** [comment] 2024-02-23 16:21
looking in to this

**Comment by ywwg** [comment] 2024-02-23 16:23
client_golang needs an update to work with this new version of common

**Comment by ywwg** [comment] 2024-02-23 20:58
Client/Common should be fixed, if you update both and still have problems please reopen

**Closed by ywwg** 2024-02-23 20:58 UTC

**Comment by beorn7** [comment] 2024-02-27 14:11
v1.19.0 of client_golang is on its way: https://github.com/prometheus/client_golang/pull/1451

Note that the prometheus/common Go module is pre v1.0, so breaking changes are happening by design.
This one is even called out in the release notes: https://github.com/prometheus/common/releases/tag/v0.48.0
I don't see value in keeping this issue open.

The fixes needed are on the side of the code using this Go module, so you could file issues over there (but in the case of prometheus/client_golang, the fix is already merged, it's just about the release, and even that is probably happening later today).

**Comment by ArthurSens** [comment] 2024-02-27 18:46
There you go!

https://github.com/prometheus/client_golang/releases/tag/v1.19.0
