### ISSUE TITLE
Version bump in prometheus/common breaks client_golang build

### ISSUE THREAD

**Issue by shane-ns1** [prometheus/common#578] opened 2024-02-26 09:00 UTC
It looks like the recent version bump of `prometheus/common` breaks the `prometheus/client_golang` build. I'm not sure whether this should be fixed in the `prometheus/common` or the `prometheus/client_golang` build (I guess probably in the `prometheus/client_golang`, but it was the `prometheus/common` version bump which broke things, so I'm filing the issue here):

```
/go/pkg/mod/github.com/prometheus/client_golang@v1.18.0/prometheus/testutil/promlint/promlint.go:71:38: undefined: expfmt.FmtText
```

Also, maybe the CI should be changed to spot these issues, since both repositories fall under the same organization in GitHub?

**Comment by SuperQ** [comment] 2024-02-26 17:48
Yes, we close issues once the code has been merged. We will need a new upstream release and bump of Go modules. But the issue can be closed to mark the fix as completed.

Duplicate of #557

**Closed** 2024-02-26 17:48 UTC
